# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: client-properties-configmap
#   namespace: subscriber
# data:
#   client_iam.properties: |
#     # security.protocol=SASL_SSL
#     # sasl.mechanism=AWS_MSK_IAM
#     # sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
#     # sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler
#     security.protocol=SASL_SSL
#     sasl.mechanism=OAUTHBEARER
#     sasl.login.callback.handler.class=io.confluent.kafka.clients.plugins.auth.token.TokenUserLoginCallbackHandler
#     sasl.login.callback.handler.class=com.yourco.kafka.OidcFileLoginCallbackHandler

apiVersion: v1
kind: ConfigMap
metadata:
  name: client-properties-configmap-producer
  namespace: confluent-cloud-aws
data:
  client_iam.properties: |
    security.protocol=SASL_SSL
    sasl.oauthbearer.token.endpoint.url=http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=${APPLICATION_CLIENT_ID}
    sasl.login.callback.handler.class=io.confluent.oauth.azure.managedidentity.OAuthBearerLoginCallbackHandler
    sasl.mechanism=OAUTHBEARER
    sasl.jaas.config= \
       org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
           clientId='ignored' \
           clientSecret='ignored' \
           extension_logicalCluster='${CLUSTER_ID}' \
           extension_identityPoolId='${PRODUCER_IDENTITY_POOL_ID}';
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-properties-configmap-consumer
  namespace: confluent-cloud-aws
data:
  client_iam.properties: |
    security.protocol=SASL_SSL
    sasl.oauthbearer.token.endpoint.url=http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=${APPLICATION_CLIENT_ID}
    sasl.login.callback.handler.class=io.confluent.oauth.azure.managedidentity.OAuthBearerLoginCallbackHandler
    sasl.mechanism=OAUTHBEARER
    sasl.jaas.config= \
       org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
           clientId='ignored' \
           clientSecret='ignored' \
           extension_logicalCluster='${CLUSTER_ID}' \
           extension_identityPoolId='${CONSUMER_IDENTITY_POOL_ID}';
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-properties-configmap-topic-owner
  namespace: confluent-cloud-aws
data:
  client_iam.properties: |
    security.protocol=SASL_SSL
    sasl.oauthbearer.token.endpoint.url=http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=${APPLICATION_CLIENT_ID}
    sasl.login.callback.handler.class=io.confluent.oauth.azure.managedidentity.OAuthBearerLoginCallbackHandler
    sasl.mechanism=OAUTHBEARER
    sasl.jaas.config= \
       org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
           clientId='ignored' \
           clientSecret='ignored' \
           extension_logicalCluster='${CLUSTER_ID}' \
           extension_identityPoolId='${TOPIC_OWNER_IDENTITY_POOL_ID}';
