include ${IAC_DIR}/modules.mk

MODULES = aws/kms/key										\
		  confluent/byok-aws								\
		  aws/kms/key-policy								\
		  aws/networking/vpc								\
		  aws/networking/security-groups/ssh-access			\
		  confluent/environment								\
		  confluent/network									\
		  confluent/private-link							\
		  confluent/cluster									\
		  aws/networking/private-link						\
		  aws/eks											\
		  aws/iam/roles/topic-owner							\
		  aws/iam/roles/consumer							\
		  aws/iam/roles/producer							\
		  aws/ec2/topic-owner								\
		  aws/ec2/consumer									\
		  aws/ec2/producer									\
		  confluent/identity-provider						\
		  confluent/identity-pool-topic-owner				\
		  confluent/identity-pool-topic-owner-permission	\
		  confluent/identity-pool-producer					\
		  confluent/identity-pool-producer-permission		\
		  confluent/identity-pool-consumer					\
		  confluent/identity-pool-consumer-permission
